// Mock data for demo mode
import { Client, Appointment, Session, Invoice, TherapistProfile, DashboardStats } from '@/types'

export const mockTherapist: TherapistProfile = {
  id: 'therapist-1',
  user_id: 'user-1',
  first_name: 'Marie',
  last_name: 'Dupont',
  phone: '+33 6 12 34 56 78',
  license_number: 'MT-2024-001234',
  company_name: 'MassageFlow Demo',
  company_address: '123 Rue de la Santé, 75001 Paris',
  company_phone: '+33 1 23 45 67 89',
  tax_rate: 20,
  slug: 'marie-dupont',
  logo_url: '',
  buffer_time: 15,
  bio: 'Massothérapeute diplômée avec 8 ans d\'expérience. Spécialisée dans le massage thérapeutique et sportif pour traiter les tensions musculaires et favoriser la récupération.',
  photo_url: '',
  instagram: 'marie.massage',
  specialties: ['Relaxation', 'Thérapeutique', 'Sportif', 'Deep tissue'],
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const mockClients: Client[] = [
  {
    id: 'client-1',
    therapist_id: 'therapist-1',
    first_name: 'Jean',
    last_name: 'Martin',
    phone: '+33 6 11 22 33 44',
    email: 'jean.martin@email.com',
    date_of_birth: '1985-03-15',
    notes: 'Client régulier, préfère les massages sportifs',
    allergies: 'Aucune',
    contraindications: 'Aucun',
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'client-2',
    therapist_id: 'therapist-1',
    first_name: 'Sophie',
    last_name: 'Bernard',
    phone: '+33 6 55 66 77 88',
    email: 'sophie.bernard@email.com',
    date_of_birth: '1990-07-22',
    notes: 'Nouvelle cliente, stress au travail',
    allergies: 'Huiles essentielles',
    contraindications: 'Femmes enceintes',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'client-3',
    therapist_id: 'therapist-1',
    first_name: 'Pierre',
    last_name: 'Durand',
    phone: '+33 6 99 88 77 66',
    email: 'pierre.durand@email.com',
    date_of_birth: '1978-11-08',
    notes: 'Douleurs chroniques au dos',
    allergies: 'Aucune',
    contraindications: 'Problèmes cardiaques',
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'client-4',
    therapist_id: 'therapist-1',
    first_name: 'Emma',
    last_name: 'Lefebvre',
    phone: '+33 6 44 33 22 11',
    email: 'emma.lefebvre@email.com',
    date_of_birth: '1995-05-30',
    notes: 'Athlète professionnelle',
    allergies: 'Aucune',
    contraindications: 'Aucune',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    therapist_id: 'therapist-1',
    client_id: 'client-1',
    date: new Date().toISOString().split('T')[0],
    start_time: '09:00',
    end_time: '10:00',
    duration: 60,
    type: 'Sportif',
    status: 'confirmed',
    notes: 'Massage post-entraînement',
    is_new_client: false,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
    client: mockClients[0],
  },
  {
    id: 'apt-2',
    therapist_id: 'therapist-1',
    client_id: 'client-2',
    date: new Date().toISOString().split('T')[0],
    start_time: '11:00',
    end_time: '12:00',
    duration: 60,
    type: 'Relaxation',
    status: 'confirmed',
    notes: 'Séance de relaxation',
    is_new_client: false,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
    client: mockClients[1],
  },
  {
    id: 'apt-3',
    therapist_id: 'therapist-1',
    client_id: 'client-3',
    date: new Date().toISOString().split('T')[0],
    start_time: '14:00',
    end_time: '15:30',
    duration: 90,
    type: 'Deep tissue',
    status: 'confirmed',
    notes: 'Massage thérapeutique',
    is_new_client: false,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
    client: mockClients[2],
  },
  {
    id: 'apt-4',
    therapist_id: 'therapist-1',
    client_id: 'client-4',
    date: new Date().toISOString().split('T')[0],
    start_time: '16:00',
    end_time: '17:00',
    duration: 60,
    type: 'Sportif',
    status: 'confirmed',
    notes: 'Préparation compétition',
    is_new_client: false,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
    client: mockClients[3],
  },
]

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    appointment_id: 'apt-1',
    therapist_id: 'therapist-1',
    client_id: 'client-1',
    date: '2024-03-10',
    duration: 60,
    massage_type: 'Sportif',
    notes: 'Massage des membres inférieurs après course',
    body_zones: 'Membres inférieurs, Dos',
    pain_areas: 'Quadriceps, Mollets',
    post_session_recommendations: 'Hydratation abondante, étirements légers',
    created_at: '2024-03-10T00:00:00Z',
    updated_at: '2024-03-10T00:00:00Z',
    client: mockClients[0],
  },
  {
    id: 'session-2',
    appointment_id: 'apt-2',
    therapist_id: 'therapist-1',
    client_id: 'client-2',
    date: '2024-03-08',
    duration: 60,
    massage_type: 'Relaxation',
    notes: 'Séance détente complète',
    body_zones: 'Dos, Épaules, Cou',
    pain_areas: 'Trapèzes, Nuque',
    post_session_recommendations: 'Repos, éviter le stress',
    created_at: '2024-03-08T00:00:00Z',
    updated_at: '2024-03-08T00:00:00Z',
    client: mockClients[1],
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: 'inv-1',
    therapist_id: 'therapist-1',
    client_id: 'client-1',
    session_id: 'session-1',
    invoice_number: '2024-0001',
    date: '2024-03-10',
    amount: 70,
    tax_rate: 20,
    tax_amount: 14,
    total_amount: 84,
    status: 'paid',
    notes: '',
    created_at: '2024-03-10T00:00:00Z',
  },
  {
    id: 'inv-2',
    therapist_id: 'therapist-1',
    client_id: 'client-2',
    session_id: 'session-2',
    invoice_number: '2024-0002',
    date: '2024-03-08',
    amount: 60,
    tax_rate: 20,
    tax_amount: 12,
    total_amount: 72,
    status: 'paid',
    notes: '',
    created_at: '2024-03-08T00:00:00Z',
  },
]

export const mockDashboardStats: DashboardStats = {
  today_appointments: 4,
  week_revenue: 420,
  new_clients: 2,
  pending_reminders: 3,
}

// Helper to get mock data based on mode
export function getMockData() {
  return {
    therapist: mockTherapist,
    clients: mockClients,
    appointments: mockAppointments,
    sessions: mockSessions,
    invoices: mockInvoices,
    stats: mockDashboardStats,
  }
}